name: whitelist_monitor
description: "Offline-first network restriction tracker and whitelist detector"
publish_to: "none"
version: 1.2.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/
